### ISSUE TITLE
make fails in WIndows

### ISSUE THREAD

**Issue by jpat34721** [vincent-picaud/MathematicaStan#1] opened 2016-10-12 15:36 UTC
I've installed the win64 version of RTools and CmdStan. I can comiple and execute the CmdStan examples from a windows powershell command line (although I always get an error message "uname: not found".
I've installed the CmdStan.m package and the Needs command executes correctly in mmy (version 11)

I'm trying to run the Bernoulli example. I've modified the top lines of Bernulli.nb as follows:

SetDirectory["C:\Users\jpat\Documents\Mathematica\STAN"]
Needs["CmdStan`"]
StanSetDirectory["C:\Users\jpat\Documents\R\cmdstan-2.12.0"]

The first directory is where Bernouilli.nb resides
the second directory is the install directory of CmdStan

The StanCompile commands barfs with:
In[53]:= StanCompile["bernoulli"]

Out[53]= "uname: not found
uname: not found
make: *_\_ No rule to make target \
`C:\Users\jpat\Documents\Mathematica\STAN\bernoulli.exe'.  \
Stop."

 I'd like to help  get your package working in Windows. I'm not familiar with make other than as a user. I am a very experienced Mathematica user with lots of .Net programming experience.

**Comment by syclik** [comment] 2016-10-12 16:55
Hi, the uname messages aren't actually errors. I haven't figured out how to
suppress it from make.

It looks like the problem is with how the target is generated. The back
slashes, '\', need to be replaced with forward slashes, '/'. I'm not sure
how to control that from Mathematica, but if you can generate the path with
forward slashes, it'll work fine. If you wanted to run it from the command
line using CmdStan, you should be able to type:

cd C:\Users\jpat\Documents\R\cmdstan-2.12.0
make C:/Users/jpat/Documents/Mathematica/STAN/bernoulli.exe

(if you run that with backslashes, it'll fail with the same error you see.)

On Oct 12, 2016, at 11:36 AM, jpat34721 notifications@github.com wrote:

I've installed the win64 version of RTools and CmdStan. I can comiple and
execute the CmdStan examples from a windows powershell command line
(although I always get an error message "uname: not found".
I've installed the CmdStan.m package and the Needs command executes
correctly in mmy (version 11)

Trying run the Bernoulli example. I've modified the top lines

SetDirectory["C:\Users\jpat\Documents\Mathematica\STAN"]
Needs["CmdStan`"]
StanSetDirectory["C:\Users\jpat\Documents\R\cmdstan-2.12.0"]

The first directory is where Bernouilli.nb resides
the second directory is the install directory of CmdStan

The StanCompile commands barfs with:
In[53]:= StanCompile["bernoulli"]

Out[53]= "uname: not found
uname: not found
make: **\* No rule to make target \
`C:\Users\jpat\Documents\Mathematica\STAN\bernoulli.exe'. \
Stop."

I'd like to help get your package working in Windows. I'm not familiar with
make other than as a user. I am a very experienced Mathematica user with
lots of .Net programming experience.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/stan-dev/MathematicaStan/issues/1, or mute the thread

**Comment by jpat34721** [comment] 2016-10-12 18:31
Hi Daniel,
Thanks for your reply. Here’s the change to CmdStan.m to fix the problem.

```
                   (*If[$OperatingSystem=="Windows",pathCodeFileName=pathCodeFileName<>".exe"];*)
                   If[$OperatingSystem=="Windows",pathCodeFileName=StringReplace[pathCodeFileName,"\\"->"/"]<>".exe"];
```

With this change the entire notebook executes fine. Good work!

Jeff

**Comment by syclik** [comment] 2016-10-12 18:48
Could you create a pull request with that change? If it's that simple to fix, awesome! Hopefully Vincent can look over the pull request: I know nothing about Mathematica.

**Comment by jpat34721** [comment] 2016-10-12 18:51
I’ve never used github so I don’t know how to do a pull request (or what a pull request is :>) Is there a documentation link you could point me to?

Thanks,
Jeff

**Comment by syclik** [comment] 2016-10-13 02:41
Hopefully you have some familiarity with git or else it'll take a few more
resources. Pull requests are GitHub's way of managing merges into a
repository.

Here's the official help:
https://help.github.com/articles/about-pull-requests/

You'll want to fork the repo (it'll put a copy of the repo in your personal
account), make the change there on a branch (it could be master), then
create a pull request from your branch to the stan-dev/mathematicastan
master branch.

It may seem like a bit much to get started, but it's not that bad once you
get the hang of it.

Daniel

On Wed, Oct 12, 2016 at 2:51 PM, Jeffery Patterson <notifications@github.com

> wrote:
> 
> I’ve never used github so I don’t know how to do a pull request (or what a
> pull request is :>) Is there a documentation link you could point me to?
> 
> Thanks,
> Jeff
> 
> From: Daniel Lee [mailto:notifications@github.com]
> Sent: Wednesday, October 12, 2016 11:48 AM
> To: stan-dev/MathematicaStan MathematicaStan@noreply.github.com
> Cc: PATTERSON,JEFF (K-Sonoma,ex1) jeff_patterson@keysight.com; Author <
> author@noreply.github.com>
> Subject: Re: [stan-dev/MathematicaStan] make fails in WIndows (#1)
> 
> Could you create a pull request with that change? If it's that simple to
> fix, awesome! Hopefully Vincent can look over the pull request: I know
> nothing about Mathematica.
> 
> > On Oct 12, 2016, at 2:31 PM, Jeffery Patterson <notifications@github.com

**Comment by vincent-picaud** [comment] 2016-10-13 13:31
Hi Jeff and Daniel,
Thank you for the fix! I am really happy to learn that this package works under Windows with your fix. I have no access to Windows and I developed it only under Linux, so it is really a good news.
Any feedback and contribution to this package are welcome,
Thank you, 
Vincent

nb: Jeff, I m going to answer to your email and add your fix right now.

**Comment by vincent-picaud** [comment] 2016-10-13 13:53
I just added your modification,
It would be nice if you can confirm that everything is running smoothly now, so that I can close the issue.
Vincent

**Comment by syclik** [comment] 2016-10-13 15:16
Thanks, all.

**Comment by jpat34721** [comment] 2016-10-13 15:54
I have verified the fix works on on all 3 examples. The notebooks need to be modified to use the window's path escapes (i.e.)

SetDirectory["C:\\Users\\jpat\\Documents\\Mathematica\\STAN\\Examples\\Bernoulli"]

and in CmdStan.m

stanDir="C:\\Users\\jpat\\Documents\\R\\cmdstan-2.12.0"; 

It would probably be good to add a note to the documentation describing the changes required to get the example notebooks to run under windows (or perhaps insert a commented out example with a note to uncomment/comment out the the appropriate lines for windows).

**Closed as completed** 2016-10-14 17:22 UTC

**Comment by vincent-picaud** [comment] 2016-10-18 15:53
Hi Jeff,

I just started to work on the "parallel sampling" feature.
My idea is to start the processes from bash (as this is currently done).
However I will have to refactor the StanRun[] function.

To check Windows power shell compatibility could you confirm me if this
code works?

#!/bin/sh

> { sleep 3; echo waking up after 3 seconds; } &
> { sleep 1; echo waking up after 1 second; } &
> wait
> echo all jobs are done!

Regards,
Vincent

2016-10-13 17:54 GMT+02:00 Jeffery Patterson notifications@github.com:

**Comment by jpat34721** [comment] 2016-10-18 18:07
Hi Vicent,

That won’t work in Windoze which has no naitive backgrounding facility. It would work with Cygwin but I think it’s a bridge too far to force the users to install and use Cygwin.

In powershell you can do something like
Start-Job  -ScriptBlock {sleep 3; echo "waking up after 3 seconds"};
Start-Job  -ScriptBlock {sleep 3; echo "waking up after 3 seconds"};
Get-Job | Wait-Job;
echo "all jobs are done!”

but this can’t be run from a normal command shell. It would have to ve saved as a ps1 file and sourced from the shell.

Hope this helpds.
Jeff

**Comment by vincent-picaud** [comment] 2016-10-18 18:19
Hi Jeff,
Yes that help me a lot because I know nothing about Windows. Thank you for
the feedback.
So what I can do is to create 2 shell scripts:
For windows your suggestion
For linux my version
I will try that tomorrow, here it is 8:20 PM
Regards,
Vincent

2016-10-18 20:07 GMT+02:00 Jeffery Patterson notifications@github.com:

**Comment by Ethiral** [comment] 2018-03-07 11:20
Hello @jpat34721  @syclik  I'm facing the same issue even though I'm using the forward slashes.
Rtools 3.3 R version 3.3 windows 10   CmdStan v2.17.1 built .
Thanks
